- name: Create folder for zsh sources
  file:
    path: $HOME/.zsh_sources
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy dotfiles
  copy:
    src: "{{ role_path }}/files/*"
    dest: "~/.zsh_sources