- name: ensure repository key is installed
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: ensure docker registry is available
  become: yes
  apt_repository: 
    repo: 'deb https://download.docker.com/linux/ubuntu eoan stable' 
    state: present
    mode: 644

- name: ensure docker and dependencies are installed
  become: yes
  apt: 
    name: docker-ce 
    update_cache: yes

- name: Restart Docker
  become: yes
  service: 
    name: docker 
    state: restarted

- name: Add user to docker group
  block:
    - name: get user 
      command: whoami
        register: current_user
    - name: add user to group docker
      user:
        name: "{{ current_user.stdout }}"
        groups: docker
        append: true
      become: yes